version: "2"

services:

  ##
  # Stack 1: Akka + Postgres
  ##
  backend1_web:
    build:
      context: backend-akka-postgres
      dockerfile: Dockerfile.web
    ports:
      - "8080:8080"
    environment:
      - SERVER_INTERFACE=0.0.0.0
      - SERVER_PORT=8080
      - DB_HOST=backend1_db
      - DB_PORT=5432
      - DB_NAME=pocdb
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - "backend1_db"

  backend1_db:
    build:
      context: backend-akka-postgres
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pocdb

  ##
  # Stack 2: Akka + OrientDB
  ##
  backend2_web:
    build:
      context: backend-akka-orientdb
      dockerfile: Dockerfile.web
    ports:
      - "8081:8080"
    environment:
      - SERVER_INTERFACE=0.0.0.0
      - SERVER_PORT=8080
      - DB_URL=remote:backend2_db/pocdb
      - DB_USER=root
      - DB_PASSWORD=rootpwd
    depends_on:
      - "backend2_db"

  backend2_db:
    build:
      context: backend-akka-orientdb
      dockerfile: Dockerfile.db
    ports:
      - "2480:2480"
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
      - ORIENT_DB=/orientdb/databases/pocdb
