version: "2"

services:

  ##
  # Frontend 1: Redux
  ##
  frontend1_web:
    build:
      context: frontend-redux
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  ##
  # Backend 1: Akka + Postgres
  ##
  backend1_web:
    build:
      context: backend-akka-postgres
      dockerfile: Dockerfile.web
    ports:
      - "8080:8080"
    environment:
      - SERVER_INTERFACE=0.0.0.0
      - SERVER_PORT=8080
      - DB_HOST=backend1_db
      - DB_PORT=5432
      - DB_NAME=pocdb
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - "backend1_db"

  backend1_db:
    build:
      context: backend-akka-postgres
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pocdb

  ##
  # Backend 2: Akka + OrientDB
  ##
  backend2_web:
    build:
      context: backend-akka-orientdb
      dockerfile: Dockerfile.web
    ports:
      - "8081:8080"
    environment:
      - SERVER_INTERFACE=0.0.0.0
      - SERVER_PORT=8080
      - DB_URL=remote:backend2_db/pocdb
      - DB_USER=root
      - DB_PASSWORD=rootpwd
    depends_on:
      - "backend2_db"

  backend2_db:
    build:
      context: backend-akka-orientdb
      dockerfile: Dockerfile.db
    ports:
      - "2480:2480"
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
      - ORIENT_DB=/orientdb/databases/pocdb

  ##
  # Backend 3: Express + ArangoDB
  ##
  backend3_web:
    build:
      context: backend-express-arangodb
      dockerfile: Dockerfile.web
    ports:
      - "8082:8080"
    environment:
      - SERVER_INTERFACE=0.0.0.0
      - SERVER_PORT=8080
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=backend3_db
      - DB_PORT=8529
      - DB_NAME=pocdb
    depends_on:
      - "backend3_db"

  backend3_db:
    build:
      context: backend-express-arangodb
      dockerfile: Dockerfile.db
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=password
